### ISSUE TITLE
Separate file for each menu

### ISSUE THREAD

**Issue by 0372JesusMtz0372** [kejonaMC/GeyserUpdater#98] opened 2023-08-11 01:12 UTC
Let there be a folder named "bedrock-forms" and inside it several .yml files and each one is the configuration of a menu, like deluxe menus

This will serve for a better personal order since if you have many menus it can be easier to locate them and you can be more organized

**Comment by Konicai** [comment] 2023-08-11 02:20
1) wrong repository lol 
2) duplicate of https://github.com/kejonaMC/CrossplatForms/issues/100

i'll try to prioritize this though :)

**Closed by Konicai** 2023-08-11 02:20 UTC

**Comment by 0372JesusMtz0372** [comment] 2023-08-11 15:59
I wish you would add it, you would be the best
